import {StyleSheet, Dimensions} from 'react-native';
export const GRAY = '#6969697a';
export const LIGHT_GRAY = '#D3D3D3';
const height = Dimensions.get('screen').height;
const width = Dimensions.get('screen').width;
export const Styles = StyleSheet.create({
  root: {
    flex: 1,
    // flexDirection: 'column',
  },
  headView: {
    flex: 1,
    marginTop: height / 2.5,
    // backgroundColor: 'red',
  },
  contentView: {
    flex: 1,
    // margin: 10,
    padding: 20,
    // backgroundColor: 'green',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footView: {
    flex: 1,
    margin: 10,
    position: 'relative',
    alignItems: 'center',
    // backgroundColor: 'blue',
    justifyContent: 'center',
  },
  welcomeText: {
    backgroundColor: 'transparent',
    color: '#fff',
    textShadowColor: 10,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Airbnb Cereal App',
    fontSize: 34,
  },
  inputAuth: {
    backgroundColor: '#ffffffa0',
    borderRadius: 10,
    paddingLeft: 6,
    width: '100%',
    margin: 10,
    minHeight: 60,
  },
  buttons: {
    left: '40%',
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffffa0',
    borderRadius: 50,
  },
  buttonsText: {
    fontSize: 17,
    fontWeight: 'bold',
    color: 'grey',
  },
  Image: {
    position: 'absolute',
    width: '180%',
    height: '100%',
    top: '-10%',
    left: '-10%',
  },
  icons: {
    height: width - 260,
    width: width - 260,
    top: '10%',
    left: '2.5%',
  },
  ball1: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: width - 20,
    height: width - 20,
    width: width - 20,
    left: '-20%',
    top: '-20%',
  },
  ball2: {
    position: 'absolute',
    borderRadius: width - 140,
    height: width - 140,
    width: width - 140,
    right: '-20%',
    top: '-15%',
  },
  ball3: {
    position: 'absolute',
    borderRadius: 30,
    height: 300,
    width: 25,
    right: '40%',
    transform: [{rotate: '-45deg'}],
  },
  ball4: {
    position: 'absolute',
    borderRadius: 30,
    height: 350,
    width: 25,
    right: '45%',
    top: '-30%',
    transform: [{rotate: '-45deg'}],
  },
  text: {
    color: '#ffffff',
    fontSize: 80,
  },
});
